name: keepass_example
description: Minimal runnable example for package:keepass.
publish_to: none
resolution: workspace
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  keepass:
    path: ../
