// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Generated bindings for keepassxc-ffi
class KeePassXcFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  KeePassXcFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  KeePassXcFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> kpxc_last_error() {
    return _kpxc_last_error();
  }

  late final _kpxc_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'kpxc_last_error');
  late final _kpxc_last_error =
      _kpxc_last_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  void kpxc_string_free(
    ffi.Pointer<ffi.Char> ptr,
  ) {
    return _kpxc_string_free(
      ptr,
    );
  }

  late final _kpxc_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'kpxc_string_free');
  late final _kpxc_string_free =
      _kpxc_string_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<KpxcDatabase> kpxc_database_open(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _kpxc_database_open(
      path,
      password,
    );
  }

  late final _kpxc_database_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<KpxcDatabase> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_database_open');
  late final _kpxc_database_open = _kpxc_database_openPtr.asFunction<
      ffi.Pointer<KpxcDatabase> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<KpxcDatabase> kpxc_database_open_with_keyfile(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Char> keyfile_path,
  ) {
    return _kpxc_database_open_with_keyfile(
      path,
      password,
      keyfile_path,
    );
  }

  late final _kpxc_database_open_with_keyfilePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<KpxcDatabase> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_database_open_with_keyfile');
  late final _kpxc_database_open_with_keyfile =
      _kpxc_database_open_with_keyfilePtr.asFunction<
          ffi.Pointer<KpxcDatabase> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  int kpxc_database_save(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _kpxc_database_save(
      db,
      path,
      password,
    );
  }

  late final _kpxc_database_savePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_database_save');
  late final _kpxc_database_save = _kpxc_database_savePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  int kpxc_database_save_with_keyfile(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Char> keyfile_path,
  ) {
    return _kpxc_database_save_with_keyfile(
      db,
      path,
      password,
      keyfile_path,
    );
  }

  late final _kpxc_database_save_with_keyfilePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_database_save_with_keyfile');
  late final _kpxc_database_save_with_keyfile =
      _kpxc_database_save_with_keyfilePtr.asFunction<
          int Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>();

  void kpxc_database_free(
    ffi.Pointer<KpxcDatabase> db,
  ) {
    return _kpxc_database_free(
      db,
    );
  }

  late final _kpxc_database_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<KpxcDatabase>)>>(
          'kpxc_database_free');
  late final _kpxc_database_free = _kpxc_database_freePtr
      .asFunction<void Function(ffi.Pointer<KpxcDatabase>)>();

  ffi.Pointer<ffi.Char> kpxc_database_root_uuid(
    ffi.Pointer<KpxcDatabase> db,
  ) {
    return _kpxc_database_root_uuid(
      db,
    );
  }

  late final _kpxc_database_root_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>)>>('kpxc_database_root_uuid');
  late final _kpxc_database_root_uuid = _kpxc_database_root_uuidPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>)>();

  ffi.Pointer<ffi.Char> kpxc_entry_get_field(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
    ffi.Pointer<ffi.Char> field_name,
  ) {
    return _kpxc_entry_get_field(
      db,
      entry_uuid,
      field_name,
    );
  }

  late final _kpxc_entry_get_fieldPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_entry_get_field');
  late final _kpxc_entry_get_field = _kpxc_entry_get_fieldPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> kpxc_entry_read_fields(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
  ) {
    return _kpxc_entry_read_fields(
      db,
      entry_uuid,
    );
  }

  late final _kpxc_entry_read_fieldsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_entry_read_fields');
  late final _kpxc_entry_read_fields = _kpxc_entry_read_fieldsPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> kpxc_entry_get_totp(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
  ) {
    return _kpxc_entry_get_totp(
      db,
      entry_uuid,
    );
  }

  late final _kpxc_entry_get_totpPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_entry_get_totp');
  late final _kpxc_entry_get_totp = _kpxc_entry_get_totpPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  int kpxc_entry_set_field(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
    ffi.Pointer<ffi.Char> field_name,
    ffi.Pointer<ffi.Char> value,
    int protected_,
  ) {
    return _kpxc_entry_set_field(
      db,
      entry_uuid,
      field_name,
      value,
      protected_,
    );
  }

  late final _kpxc_entry_set_fieldPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int)>>('kpxc_entry_set_field');
  late final _kpxc_entry_set_field = _kpxc_entry_set_fieldPtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<ffi.Char> kpxc_entry_get_uuid(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
    int index,
  ) {
    return _kpxc_entry_get_uuid(
      db,
      group_uuid,
      index,
    );
  }

  late final _kpxc_entry_get_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>, ffi.UintPtr)>>('kpxc_entry_get_uuid');
  late final _kpxc_entry_get_uuid = _kpxc_entry_get_uuidPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<ffi.Char> kpxc_entry_create(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_entry_create(
      db,
      group_uuid,
    );
  }

  late final _kpxc_entry_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_entry_create');
  late final _kpxc_entry_create = _kpxc_entry_createPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  int kpxc_entry_delete(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
    int permanent,
  ) {
    return _kpxc_entry_delete(
      db,
      entry_uuid,
      permanent,
    );
  }

  late final _kpxc_entry_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('kpxc_entry_delete');
  late final _kpxc_entry_delete = _kpxc_entry_deletePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  int kpxc_entry_move(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
    ffi.Pointer<ffi.Char> target_group_uuid,
  ) {
    return _kpxc_entry_move(
      db,
      entry_uuid,
      target_group_uuid,
    );
  }

  late final _kpxc_entry_movePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_entry_move');
  late final _kpxc_entry_move = _kpxc_entry_movePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> kpxc_group_get_name(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_group_get_name(
      db,
      group_uuid,
    );
  }

  late final _kpxc_group_get_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_get_name');
  late final _kpxc_group_get_name = _kpxc_group_get_namePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  int kpxc_group_set_name(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _kpxc_group_set_name(
      db,
      group_uuid,
      name,
    );
  }

  late final _kpxc_group_set_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_set_name');
  late final _kpxc_group_set_name = _kpxc_group_set_namePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> kpxc_group_get_uuid(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> parent_uuid,
    int index,
  ) {
    return _kpxc_group_get_uuid(
      db,
      parent_uuid,
      index,
    );
  }

  late final _kpxc_group_get_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>, ffi.UintPtr)>>('kpxc_group_get_uuid');
  late final _kpxc_group_get_uuid = _kpxc_group_get_uuidPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  int kpxc_group_entries_count(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_group_entries_count(
      db,
      group_uuid,
    );
  }

  late final _kpxc_group_entries_countPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_entries_count');
  late final _kpxc_group_entries_count =
      _kpxc_group_entries_countPtr.asFunction<
          int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  int kpxc_group_groups_count(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_group_groups_count(
      db,
      group_uuid,
    );
  }

  late final _kpxc_group_groups_countPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_groups_count');
  late final _kpxc_group_groups_count = _kpxc_group_groups_countPtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> kpxc_group_create(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> parent_uuid,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _kpxc_group_create(
      db,
      parent_uuid,
      name,
    );
  }

  late final _kpxc_group_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_create');
  late final _kpxc_group_create = _kpxc_group_createPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  int kpxc_group_delete(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
    int permanent,
  ) {
    return _kpxc_group_delete(
      db,
      group_uuid,
      permanent,
    );
  }

  late final _kpxc_group_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('kpxc_group_delete');
  late final _kpxc_group_delete = _kpxc_group_deletePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<ffi.Char> kpxc_group_root_uuid(
    ffi.Pointer<KpxcDatabase> db,
  ) {
    return _kpxc_group_root_uuid(
      db,
    );
  }

  late final _kpxc_group_root_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>)>>('kpxc_group_root_uuid');
  late final _kpxc_group_root_uuid = _kpxc_group_root_uuidPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>)>();

  int kpxc_group_move(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
    ffi.Pointer<ffi.Char> target_parent_uuid,
  ) {
    return _kpxc_group_move(
      db,
      group_uuid,
      target_parent_uuid,
    );
  }

  late final _kpxc_group_movePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_move');
  late final _kpxc_group_move = _kpxc_group_movePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> kpxc_database_merge(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<KpxcDatabase> other,
  ) {
    return _kpxc_database_merge(
      db,
      other,
    );
  }

  late final _kpxc_database_mergePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<KpxcDatabase>)>>('kpxc_database_merge');
  late final _kpxc_database_merge = _kpxc_database_mergePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<KpxcDatabase>)>();

  ffi.Pointer<KpxcDatabase> kpxc_database_open_with_yubikey(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Char> slot,
    int serial,
  ) {
    return _kpxc_database_open_with_yubikey(
      path,
      password,
      slot,
      serial,
    );
  }

  late final _kpxc_database_open_with_yubikeyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<KpxcDatabase> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Uint32)>>('kpxc_database_open_with_yubikey');
  late final _kpxc_database_open_with_yubikey =
      _kpxc_database_open_with_yubikeyPtr.asFunction<
          ffi.Pointer<KpxcDatabase> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<ffi.Char> kpxc_yubikey_list() {
    return _kpxc_yubikey_list();
  }

  late final _kpxc_yubikey_listPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'kpxc_yubikey_list');
  late final _kpxc_yubikey_list =
      _kpxc_yubikey_listPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class KpxcDatabase extends ffi.Opaque {}

const int KPXC_OK = 0;

const int KPXC_ERR_IO = -1;

const int KPXC_ERR_OPEN = -2;

const int KPXC_ERR_SAVE = -3;

const int KPXC_ERR_NOT_FOUND = -4;

const int KPXC_ERR_MERGE = -5;

const int KPXC_ERR_YUBIKEY = -6;

const int KPXC_ERR_NULL_PTR = -7;

const int KPXC_ERR_INVALID_UTF8 = -8;
