// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Generated bindings for keepassxc-ffi
class KeePassXcFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  KeePassXcFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  KeePassXcFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Return a pointer to the last error message string (UTF-8, null-terminated).
  ///
  /// The returned pointer is valid until the next FFI call on the same thread.
  /// Returns null if no error has occurred.
  ffi.Pointer<ffi.Char> kpxc_last_error() {
    return _kpxc_last_error();
  }

  late final _kpxc_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'kpxc_last_error');
  late final _kpxc_last_error =
      _kpxc_last_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Free a string that was returned by an FFI function.
  ///
  /// The caller must pass only pointers that were returned by kpxc_* functions
  /// (e.g., `kpxc_entry_get_field`, `kpxc_database_merge`).
  /// Passing null is a no-op.
  void kpxc_string_free(
    ffi.Pointer<ffi.Char> ptr,
  ) {
    return _kpxc_string_free(
      ptr,
    );
  }

  late final _kpxc_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'kpxc_string_free');
  late final _kpxc_string_free =
      _kpxc_string_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Open a KDBX database with a password.
  ///
  /// Returns a heap-allocated `KpxcDatabase` handle, or null on error.
  /// The caller must free the handle with `kpxc_database_free`.
  ffi.Pointer<KpxcDatabase> kpxc_database_open(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _kpxc_database_open(
      path,
      password,
    );
  }

  late final _kpxc_database_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<KpxcDatabase> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_database_open');
  late final _kpxc_database_open = _kpxc_database_openPtr.asFunction<
      ffi.Pointer<KpxcDatabase> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Open a KDBX database with a password and key file.
  ///
  /// Returns a heap-allocated `KpxcDatabase` handle, or null on error.
  /// The caller must free the handle with `kpxc_database_free`.
  ffi.Pointer<KpxcDatabase> kpxc_database_open_with_keyfile(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Char> keyfile_path,
  ) {
    return _kpxc_database_open_with_keyfile(
      path,
      password,
      keyfile_path,
    );
  }

  late final _kpxc_database_open_with_keyfilePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<KpxcDatabase> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_database_open_with_keyfile');
  late final _kpxc_database_open_with_keyfile =
      _kpxc_database_open_with_keyfilePtr.asFunction<
          ffi.Pointer<KpxcDatabase> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Save a database to a file path with a password.
  ///
  /// Returns `KPXC_OK` on success, negative error code on failure.
  int kpxc_database_save(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _kpxc_database_save(
      db,
      path,
      password,
    );
  }

  late final _kpxc_database_savePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_database_save');
  late final _kpxc_database_save = _kpxc_database_savePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// Free a database handle.
  ///
  /// Passing null is a no-op.
  void kpxc_database_free(
    ffi.Pointer<KpxcDatabase> db,
  ) {
    return _kpxc_database_free(
      db,
    );
  }

  late final _kpxc_database_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<KpxcDatabase>)>>(
          'kpxc_database_free');
  late final _kpxc_database_free = _kpxc_database_freePtr
      .asFunction<void Function(ffi.Pointer<KpxcDatabase>)>();

  /// Return the UUID string of the root group.
  ///
  /// Returns a heap-allocated string (caller frees with `kpxc_string_free`),
  /// or null on error.
  ffi.Pointer<ffi.Char> kpxc_database_root_uuid(
    ffi.Pointer<KpxcDatabase> db,
  ) {
    return _kpxc_database_root_uuid(
      db,
    );
  }

  late final _kpxc_database_root_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>)>>('kpxc_database_root_uuid');
  late final _kpxc_database_root_uuid = _kpxc_database_root_uuidPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>)>();

  /// Get a field value from an entry identified by UUID.
  ///
  /// Returns a heap-allocated string (caller frees with `kpxc_string_free`),
  /// or null if the entry/field is not found.
  ffi.Pointer<ffi.Char> kpxc_entry_get_field(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
    ffi.Pointer<ffi.Char> field_name,
  ) {
    return _kpxc_entry_get_field(
      db,
      entry_uuid,
      field_name,
    );
  }

  late final _kpxc_entry_get_fieldPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_entry_get_field');
  late final _kpxc_entry_get_field = _kpxc_entry_get_fieldPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Set a field value on an entry identified by UUID (with history tracking).
  ///
  /// `protected`: 1 for protected (e.g., Password), 0 for unprotected.
  /// Returns `KPXC_OK` on success.
  int kpxc_entry_set_field(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
    ffi.Pointer<ffi.Char> field_name,
    ffi.Pointer<ffi.Char> value,
    int protected_,
  ) {
    return _kpxc_entry_set_field(
      db,
      entry_uuid,
      field_name,
      value,
      protected_,
    );
  }

  late final _kpxc_entry_set_fieldPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int)>>('kpxc_entry_set_field');
  late final _kpxc_entry_set_field = _kpxc_entry_set_fieldPtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  /// Get the UUID of an entry at the given index within a group.
  ///
  /// Returns a heap-allocated UUID string (caller frees with `kpxc_string_free`),
  /// or null on error.
  ffi.Pointer<ffi.Char> kpxc_entry_get_uuid(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
    int index,
  ) {
    return _kpxc_entry_get_uuid(
      db,
      group_uuid,
      index,
    );
  }

  late final _kpxc_entry_get_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>, ffi.UintPtr)>>('kpxc_entry_get_uuid');
  late final _kpxc_entry_get_uuid = _kpxc_entry_get_uuidPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  /// Create a new entry in the specified group.
  ///
  /// Returns the new entry's UUID string (caller frees with `kpxc_string_free`),
  /// or null on error.
  ffi.Pointer<ffi.Char> kpxc_entry_create(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_entry_create(
      db,
      group_uuid,
    );
  }

  late final _kpxc_entry_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_entry_create');
  late final _kpxc_entry_create = _kpxc_entry_createPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  /// Delete an entry by UUID.
  ///
  /// If `permanent` is 0, soft-deletes (moves to recycle bin).
  /// If `permanent` is 1, hard-deletes (removes entirely).
  /// Returns `KPXC_OK` on success.
  int kpxc_entry_delete(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> entry_uuid,
    int permanent,
  ) {
    return _kpxc_entry_delete(
      db,
      entry_uuid,
      permanent,
    );
  }

  late final _kpxc_entry_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('kpxc_entry_delete');
  late final _kpxc_entry_delete = _kpxc_entry_deletePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  /// Get the name of a group identified by UUID.
  ///
  /// Returns a heap-allocated string (caller frees with `kpxc_string_free`),
  /// or null if the group is not found.
  ffi.Pointer<ffi.Char> kpxc_group_get_name(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_group_get_name(
      db,
      group_uuid,
    );
  }

  late final _kpxc_group_get_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_get_name');
  late final _kpxc_group_get_name = _kpxc_group_get_namePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  /// Set the name of a group identified by UUID.
  ///
  /// Returns `KPXC_OK` on success.
  int kpxc_group_set_name(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _kpxc_group_set_name(
      db,
      group_uuid,
      name,
    );
  }

  late final _kpxc_group_set_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_set_name');
  late final _kpxc_group_set_name = _kpxc_group_set_namePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// Get the UUID of a child group at the given index within a parent group.
  ///
  /// Returns a heap-allocated UUID string (caller frees with `kpxc_string_free`),
  /// or null on error.
  ffi.Pointer<ffi.Char> kpxc_group_get_uuid(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> parent_uuid,
    int index,
  ) {
    return _kpxc_group_get_uuid(
      db,
      parent_uuid,
      index,
    );
  }

  late final _kpxc_group_get_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>, ffi.UintPtr)>>('kpxc_group_get_uuid');
  late final _kpxc_group_get_uuid = _kpxc_group_get_uuidPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  /// Get the number of direct entries in a group.
  ///
  /// Returns the count (>= 0) on success, or a negative error code.
  int kpxc_group_entries_count(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_group_entries_count(
      db,
      group_uuid,
    );
  }

  late final _kpxc_group_entries_countPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_entries_count');
  late final _kpxc_group_entries_count =
      _kpxc_group_entries_countPtr.asFunction<
          int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  /// Get the number of direct child groups in a group.
  ///
  /// Returns the count (>= 0) on success, or a negative error code.
  int kpxc_group_groups_count(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
  ) {
    return _kpxc_group_groups_count(
      db,
      group_uuid,
    );
  }

  late final _kpxc_group_groups_countPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_groups_count');
  late final _kpxc_group_groups_count = _kpxc_group_groups_countPtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>)>();

  /// Create a new child group under the specified parent.
  ///
  /// Returns the new group's UUID string (caller frees with `kpxc_string_free`),
  /// or null on error.
  ffi.Pointer<ffi.Char> kpxc_group_create(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> parent_uuid,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _kpxc_group_create(
      db,
      parent_uuid,
      name,
    );
  }

  late final _kpxc_group_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('kpxc_group_create');
  late final _kpxc_group_create = _kpxc_group_createPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Delete a group by UUID.
  ///
  /// If `permanent` is 0, soft-deletes (moves to recycle bin).
  /// If `permanent` is 1, hard-deletes (removes entirely).
  /// Returns `KPXC_OK` on success.
  int kpxc_group_delete(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<ffi.Char> group_uuid,
    int permanent,
  ) {
    return _kpxc_group_delete(
      db,
      group_uuid,
      permanent,
    );
  }

  late final _kpxc_group_deletePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>,
              ffi.Int)>>('kpxc_group_delete');
  late final _kpxc_group_delete = _kpxc_group_deletePtr.asFunction<
      int Function(ffi.Pointer<KpxcDatabase>, ffi.Pointer<ffi.Char>, int)>();

  /// Return the root group UUID string.
  ///
  /// Returns a heap-allocated string (caller frees with `kpxc_string_free`),
  /// or null on error. This is a convenience alias for `kpxc_database_root_uuid`.
  ffi.Pointer<ffi.Char> kpxc_group_root_uuid(
    ffi.Pointer<KpxcDatabase> db,
  ) {
    return _kpxc_group_root_uuid(
      db,
    );
  }

  late final _kpxc_group_root_uuidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<KpxcDatabase>)>>('kpxc_group_root_uuid');
  late final _kpxc_group_root_uuid = _kpxc_group_root_uuidPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>)>();

  /// Merge `other` into `db`, returning a JSON string with merge statistics.
  ///
  /// `db` is mutated in place. `other` is read-only.
  /// Returns a heap-allocated JSON string (caller frees with `kpxc_string_free`),
  /// or null on error.
  ///
  /// IMPORTANT: Both `db` and `other` must be valid, distinct pointers.
  ffi.Pointer<ffi.Char> kpxc_database_merge(
    ffi.Pointer<KpxcDatabase> db,
    ffi.Pointer<KpxcDatabase> other,
  ) {
    return _kpxc_database_merge(
      db,
      other,
    );
  }

  late final _kpxc_database_mergePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<KpxcDatabase>,
              ffi.Pointer<KpxcDatabase>)>>('kpxc_database_merge');
  late final _kpxc_database_merge = _kpxc_database_mergePtr.asFunction<
      ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<KpxcDatabase>, ffi.Pointer<KpxcDatabase>)>();

  /// Open a KDBX database with password + YubiKey challenge-response.
  ///
  /// `slot` is the YubiKey slot ("1" or "2").
  /// `serial` is the YubiKey serial number; pass 0 to use the first detected YubiKey.
  ///
  /// Returns a heap-allocated `KpxcDatabase` handle, or null on error.
  ffi.Pointer<KpxcDatabase> kpxc_database_open_with_yubikey(
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Char> slot,
    int serial,
  ) {
    return _kpxc_database_open_with_yubikey(
      path,
      password,
      slot,
      serial,
    );
  }

  late final _kpxc_database_open_with_yubikeyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<KpxcDatabase> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Uint32)>>('kpxc_database_open_with_yubikey');
  late final _kpxc_database_open_with_yubikey =
      _kpxc_database_open_with_yubikeyPtr.asFunction<
          ffi.Pointer<KpxcDatabase> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)>();

  /// List all connected YubiKey devices capable of challenge-response.
  ///
  /// Returns a JSON array string like `[{"serial_number":12345,"name":"YubiKey 5"}]`.
  /// Caller frees with `kpxc_string_free`. Returns null on error.
  ffi.Pointer<ffi.Char> kpxc_yubikey_list() {
    return _kpxc_yubikey_list();
  }

  late final _kpxc_yubikey_listPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'kpxc_yubikey_list');
  late final _kpxc_yubikey_list =
      _kpxc_yubikey_listPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class KpxcDatabase extends ffi.Opaque {}

const int KPXC_OK = 0;

const int KPXC_ERR_IO = -1;

const int KPXC_ERR_OPEN = -2;

const int KPXC_ERR_SAVE = -3;

const int KPXC_ERR_NOT_FOUND = -4;

const int KPXC_ERR_MERGE = -5;

const int KPXC_ERR_YUBIKEY = -6;

const int KPXC_ERR_NULL_PTR = -7;

const int KPXC_ERR_INVALID_UTF8 = -8;
